from core.models import Language

english = Language.objects.get_or_create(name="English", frequency=141264)[0]
german = Language.objects.get_or_create(name="German", frequency=20058)[0]
french = Language.objects.get_or_create(name="French", frequency=19617)[0]
spanish = Language.objects.get_or_create(name="Spanish", frequency=17669)[0]
japanese = Language.objects.get_or_create(name="Japanese", frequency=13530)[0]
Language.objects.get_or_create(name="Russian", frequency=11837)[0]
Language.objects.get_or_create(name="Italian", frequency=8672)[0]
chinese = Language.objects.get_or_create(name="Chinese", frequency=8439)[0]
Language.objects.get_or_create(name="Portuguese", frequency=5765)[0]
farsi = Language.objects.get_or_create(name="Persian", frequency=4727)[0]
Language.objects.get_or_create(name="Polish", frequency=4551)[0]
arabic = Language.objects.get_or_create(name="Arabic", frequency=4535)[0]
Language.objects.get_or_create(name="Dutch", frequency=4436)[0]
Language.objects.get_or_create(name="Ukrainian", frequency=3228)[0]
hebrew = Language.objects.get_or_create(name="Hebrew", frequency=3059)[0]
Language.objects.get_or_create(name="Swedish", frequency=2918)[0]
Language.objects.get_or_create(name="Indonesian", frequency=2700)[0]
Language.objects.get_or_create(name="Czech", frequency=2401)[0]
korean = Language.objects.get_or_create(name="Korean", frequency=2013)[0]
Language.objects.get_or_create(name="Finnish", frequency=1956)[0]
Language.objects.get_or_create(name="Hungarian", frequency=1858)[0]
vietnamese = Language.objects.get_or_create(name="Vietnamese", frequency=1798)[0]
Language.objects.get_or_create(name="Catalan", frequency=1773)[0]
Language.objects.get_or_create(name="Norwegian (Bokmål)", frequency=1608)[0]
thai = Language.objects.get_or_create(name="Thai", frequency=1453)[0]
hindi = Language.objects.get_or_create(name="Hindi", frequency=1406)[0]
Language.objects.get_or_create(name="Danish", frequency=1151)[0]
Language.objects.get_or_create(name="Romanian", frequency=1128)[0]
greek = Language.objects.get_or_create(name="Greek", frequency=1102)[0]
koine_greek = Language.objects.get_or_create(name="Koine Greek", frequency=0)[0]
Language.objects.get_or_create(name="Serbian", frequency=1082)[0]
Language.objects.get_or_create(name="Bengali", frequency=996)[0]
Language.objects.get_or_create(name="Simple English", frequency=855)[0]
Language.objects.get_or_create(name="Turkish", frequency=803)[0]
Language.objects.get_or_create(name="Bulgarian", frequency=793)[0]
Language.objects.get_or_create(name="Armenian", frequency=785)[0]
Language.objects.get_or_create(name="Azerbaijani", frequency=668)[0]
Language.objects.get_or_create(name="Basque", frequency=660)[0]
Language.objects.get_or_create(name="Estonian", frequency=648)[0]
Language.objects.get_or_create(name="Croatian", frequency=554)[0]
Language.objects.get_or_create(name="Slovak", frequency=552)[0]
Language.objects.get_or_create(name="Malay", frequency=519)[0]
Language.objects.get_or_create(name="Galician", frequency=462)[0]
Language.objects.get_or_create(name="Slovenian", frequency=426)[0]
Language.objects.get_or_create(name="Tamil", frequency=401)[0]
Language.objects.get_or_create(name="Esperanto", frequency=390)[0]
Language.objects.get_or_create(name="Malayalam", frequency=361)[0]
Language.objects.get_or_create(name="Lithuanian", frequency=359)[0]
Language.objects.get_or_create(name="Marathi", frequency=355)[0]
Language.objects.get_or_create(name="Georgian", frequency=327)[0]
Language.objects.get_or_create(name="Albanian", frequency=301)[0]
Language.objects.get_or_create(name="Kannada", frequency=300)[0]
Language.objects.get_or_create(name="Latvian", frequency=297)[0]
Language.objects.get_or_create(name="Urdu", frequency=274)[0]
Language.objects.get_or_create(name="Belarusian", frequency=268)[0]
Language.objects.get_or_create(name="Macedonian", frequency=260)[0]
Language.objects.get_or_create(name="Cantonese", frequency=254)[0]
Language.objects.get_or_create(name="Kazakh", frequency=233)[0]
Language.objects.get_or_create(name="Serbo-Croatian", frequency=203)[0]
Language.objects.get_or_create(name="Icelandic", frequency=191)[0]
Language.objects.get_or_create(name="Bosnian", frequency=187)[0]
Language.objects.get_or_create(name="Cebuano", frequency=172)[0]
Language.objects.get_or_create(name="Telugu", frequency=170)[0]
Language.objects.get_or_create(name="Afrikaans", frequency=166)[0]
Language.objects.get_or_create(name="Norwegian (Nynorsk)", frequency=162)[0]
latin = Language.objects.get_or_create(name="Latin", frequency=158)[0]
Language.objects.get_or_create(name="Asturian", frequency=158)[0]
welsh = Language.objects.get_or_create(name="Welsh", frequency=154)[0]
Language.objects.get_or_create(name="Tagalog", frequency=145)[0]
Language.objects.get_or_create(name="Javanese", frequency=136)[0]
Language.objects.get_or_create(name="Konkani", frequency=136)[0]
sanskrit = Language.objects.get_or_create(name="Sanskrit", frequency=134)[0]
Language.objects.get_or_create(name="Uzbek", frequency=129)[0]
uzbek = Language.objects.get_or_create(name="Uzbek", frequency=129)[0]
swahili = Language.objects.get_or_create(name="Swahili", frequency=129)[0]
Language.objects.get_or_create(name="Belarusian (Taraškievica)", frequency=122)[0]
Language.objects.get_or_create(name="Breton", frequency=115)[0]
Language.objects.get_or_create(name="Mongolian", frequency=115)[0]
Language.objects.get_or_create(name="Burmese", frequency=114)[0]
Language.objects.get_or_create(name="Egyptian Arabic", frequency=110)[0]
egyptian = Language.objects.get_or_create(name="Ancient Egyptian", frequency=0)[0]
irish = Language.objects.get_or_create(name="Irish", frequency=108)[0]
Language.objects.get_or_create(name="Eastern Punjabi", frequency=108)[0]
Language.objects.get_or_create(name="Scots", frequency=106)[0]
Language.objects.get_or_create(name="Kurdish (Sorani)", frequency=105)[0]
Language.objects.get_or_create(name="Nepali", frequency=100)[0]
Language.objects.get_or_create(name="Luxembourgish", frequency=97)[0]
Language.objects.get_or_create(name="Southern Azerbaijani", frequency=95)[0]
Language.objects.get_or_create(name="Alemannic", frequency=94)[0]
Language.objects.get_or_create(name="Occitan", frequency=92)[0]
Language.objects.get_or_create(name="Tatar", frequency=88)[0]
Language.objects.get_or_create(name="Gujarati", frequency=84)[0]
Language.objects.get_or_create(name="Classical Chinese", frequency=83)[0]
Language.objects.get_or_create(name="Bashkir", frequency=82)[0]
Language.objects.get_or_create(name="Waray", frequency=81)[0]
Language.objects.get_or_create(name="Assamese", frequency=78)[0]
Language.objects.get_or_create(name="Sundanese", frequency=76)[0]
Language.objects.get_or_create(name="Somali", frequency=76)[0]
Language.objects.get_or_create(name="Kirghiz", frequency=74)[0]
Language.objects.get_or_create(name="Khmer", frequency=72)[0]
Language.objects.get_or_create(name="West Frisian", frequency=71)[0]
Language.objects.get_or_create(name="Aragonese", frequency=69)[0]
Language.objects.get_or_create(name="Min Nan", frequency=68)[0]
Language.objects.get_or_create(name="Tajik", frequency=68)[0]
Language.objects.get_or_create(name="Sinhalese", frequency=68)[0]
Language.objects.get_or_create(name="Bavarian", frequency=67)[0]
Language.objects.get_or_create(name="Minangkabau", frequency=65)[0]
Language.objects.get_or_create(name="Kurdish (Kurmanji)", frequency=63)[0]
Language.objects.get_or_create(name="Odia", frequency=62)[0]
Language.objects.get_or_create(name="Yiddish", frequency=55)[0]
Language.objects.get_or_create(name="Low Saxon", frequency=52)[0]
Language.objects.get_or_create(name="Wu", frequency=52)[0]
Language.objects.get_or_create(name="Amharic", frequency=50)[0]
Language.objects.get_or_create(name="Interlingua", frequency=48)[0]
Language.objects.get_or_create(name="Anglo-Saxon", frequency=48)[0]
Language.objects.get_or_create(name="Lombard", frequency=47)[0]
afghan = Language.objects.get_or_create(name="Pashto", frequency=47)[0]
Language.objects.get_or_create(name="Malagasy", frequency=45)[0]
Language.objects.get_or_create(name="Bhojpuri", frequency=44)[0]
Language.objects.get_or_create(name="Venetian", frequency=43)[0]
Language.objects.get_or_create(name="Ido", frequency=42)[0]
Language.objects.get_or_create(name="Sindhi", frequency=42)[0]
Language.objects.get_or_create(name="Maltese", frequency=42)[0]
Language.objects.get_or_create(name="Western Punjabi", frequency=41)[0]
Language.objects.get_or_create(name="Faroese", frequency=41)[0]
Language.objects.get_or_create(name="Chechen", frequency=40)[0]
Language.objects.get_or_create(name="Limburgish", frequency=40)[0]
Language.objects.get_or_create(name="Chuvash", frequency=38)[0]
Language.objects.get_or_create(name="Central Bicolano", frequency=38)[0]
Language.objects.get_or_create(name="Turkmen", frequency=38)[0]
yoruba = Language.objects.get_or_create(name="Yoruba", frequency=37)[0]
Language.objects.get_or_create(name="Maithili", frequency=37)[0]
Language.objects.get_or_create(name="Sicilian", frequency=36)[0]
Language.objects.get_or_create(name="Haitian", frequency=34)[0]
Language.objects.get_or_create(name="Mazandarani", frequency=34)[0]
Language.objects.get_or_create(name="Sakha", frequency=34)[0]
quechua = Language.objects.get_or_create(name="Quechua", frequency=33)[0]
Language.objects.get_or_create(name="West Flemish", frequency=33)[0]
Language.objects.get_or_create(name="Mingrelian", frequency=32)[0]
Language.objects.get_or_create(name="Fiji Hindi", frequency=32)[0]
Language.objects.get_or_create(name="Zulu", frequency=32)[0]
Language.objects.get_or_create(name="Bishnupriya Manipuri", frequency=31)[0]
gaelic = Language.objects.get_or_create(name="Scottish Gaelic", frequency=31)[0]
Language.objects.get_or_create(name="Tibetan", frequency=31)[0]
Language.objects.get_or_create(name="Piedmontese", frequency=30)[0]
Language.objects.get_or_create(name="Zazaki", frequency=30)[0]
Language.objects.get_or_create(name="Dutch Low Saxon", frequency=30)[0]
Language.objects.get_or_create(name="Volapük", frequency=29)[0]
Language.objects.get_or_create(name="Newar", frequency=29)[0]
Language.objects.get_or_create(name="Upper Sorbian", frequency=29)[0]
Language.objects.get_or_create(name="Hakka", frequency=29)[0]
Language.objects.get_or_create(name="Santali", frequency=29)[0]
Language.objects.get_or_create(name="Samogitian", frequency=28)[0]
Language.objects.get_or_create(name="Banyumasan", frequency=27)[0]
Language.objects.get_or_create(name="Northern Sami", frequency=27)[0]
Language.objects.get_or_create(name="Sardinian", frequency=27)[0]
Language.objects.get_or_create(name="Lao", frequency=27)[0]
Language.objects.get_or_create(name="Igbo", frequency=27)[0]
Language.objects.get_or_create(name="Acehnese", frequency=26)[0]
Language.objects.get_or_create(name="Northern Luri", frequency=26)[0]
Language.objects.get_or_create(name="Old Church Slavonic", frequency=26)[0]
Language.objects.get_or_create(name="North Frisian", frequency=25)[0]
Language.objects.get_or_create(name="Rusyn", frequency=25)[0]
Language.objects.get_or_create(name="Crimean Tatar", frequency=25)[0]
Language.objects.get_or_create(name="Ligurian", frequency=25)[0]
Language.objects.get_or_create(name="Hausa", frequency=25)[0]
Language.objects.get_or_create(name="Tulu", frequency=25)[0]
Language.objects.get_or_create(name="Cherokee", frequency=25)[0]
Language.objects.get_or_create(name="Xhosa", frequency=25)[0]
Language.objects.get_or_create(name="Ilocano", frequency=24)[0]
Language.objects.get_or_create(name="Meadow Mari", frequency=24)[0]
Language.objects.get_or_create(name="Vepsian", frequency=24)[0]
Language.objects.get_or_create(name="Picard", frequency=24)[0]
Language.objects.get_or_create(name="Interlingue", frequency=24)[0]
Language.objects.get_or_create(name="Ladino", frequency=24)[0]
Language.objects.get_or_create(name="Emilian-Romagnol", frequency=23)[0]
Language.objects.get_or_create(name="Ossetian", frequency=23)[0]
Language.objects.get_or_create(name="Extremaduran", frequency=23)[0]
Language.objects.get_or_create(name="Buginese", frequency=22)[0]
Language.objects.get_or_create(name="Silesian", frequency=22)[0]
Language.objects.get_or_create(name="Maori", frequency=22)[0]
Language.objects.get_or_create(name="Corsican", frequency=22)[0]
Language.objects.get_or_create(name="Kashubian", frequency=22)[0]
Language.objects.get_or_create(name="Friulian", frequency=22)[0]
Language.objects.get_or_create(name="Manx", frequency=21)[0]
Language.objects.get_or_create(name="Chavacano", frequency=21)[0]
Language.objects.get_or_create(name="Doteli", frequency=21)[0]
Language.objects.get_or_create(name="Buryat", frequency=21)[0]
Language.objects.get_or_create(name="Neapolitan", frequency=20)[0]
Language.objects.get_or_create(name="Erzya", frequency=20)[0]
Language.objects.get_or_create(name="Lezgian", frequency=20)[0]
Language.objects.get_or_create(name="Guarani", frequency=20)[0]
Language.objects.get_or_create(name="Romansh", frequency=20)[0]
Language.objects.get_or_create(name="Papiamentu", frequency=20)[0]
Language.objects.get_or_create(name="Pennsylvania German", frequency=20)[0]
Language.objects.get_or_create(name="Min Dong", frequency=19)[0]
Language.objects.get_or_create(name="Kapampangan", frequency=19)[0]
nahuatl = Language.objects.get_or_create(name="Nahuatl", frequency=19)[0]
Language.objects.get_or_create(name="Gan", frequency=19)[0]
Language.objects.get_or_create(name="Cornish", frequency=19)[0]
Language.objects.get_or_create(name="Mirandese", frequency=19)[0]
Language.objects.get_or_create(name="Lingua Franca Nova", frequency=19)[0]
Language.objects.get_or_create(name="Lower Sorbian", frequency=19)[0]
Language.objects.get_or_create(name="Divehi", frequency=19)[0]
Language.objects.get_or_create(name="Gorontalo", frequency=19)[0]
Language.objects.get_or_create(name="Zhuang", frequency=19)[0]
Language.objects.get_or_create(name="Gothic", frequency=19)[0]
Language.objects.get_or_create(name="Dzongkha", frequency=19)[0]
Language.objects.get_or_create(name="Walloon", frequency=18)[0]
Language.objects.get_or_create(name="Komi", frequency=18)[0]
Language.objects.get_or_create(name="Uyghur", frequency=18)[0]
Language.objects.get_or_create(name="Abkhazian", frequency=18)[0]
Language.objects.get_or_create(name="Wolof", frequency=18)[0]
Language.objects.get_or_create(name="Atikamekw", frequency=18)[0]
Language.objects.get_or_create(name="Norman", frequency=17)[0]
Language.objects.get_or_create(name="Livvi-Karelian", frequency=17)[0]
Language.objects.get_or_create(name="Palatinate German", frequency=17)[0]
Language.objects.get_or_create(name="Avar", frequency=17)[0]
Language.objects.get_or_create(name="Tuvan", frequency=17)[0]
Language.objects.get_or_create(name="Aromanian", frequency=17)[0]
Language.objects.get_or_create(name="Chichewa", frequency=17)[0]
Language.objects.get_or_create(name="Hill Mari", frequency=16)[0]
Language.objects.get_or_create(name="Zeelandic", frequency=16)[0]
Language.objects.get_or_create(name="Udmurt", frequency=16)[0]
Language.objects.get_or_create(name="Shona", frequency=16)[0]
Language.objects.get_or_create(name="Saterland Frisian", frequency=16)[0]
Language.objects.get_or_create(name="Lingala", frequency=16)[0]
Language.objects.get_or_create(name="Kabyle", frequency=16)[0]
Language.objects.get_or_create(name="Ripuarian", frequency=16)[0]
Language.objects.get_or_create(name="Gagauz", frequency=16)[0]
Language.objects.get_or_create(name="Banjar", frequency=16)[0]
Language.objects.get_or_create(name="Bislama", frequency=16)[0]
oromo = Language.objects.get_or_create(name="Oromo", frequency=16)[0]
Language.objects.get_or_create(name="Norfolk", frequency=16)[0]
Language.objects.get_or_create(name="Twi", frequency=16)[0]
Language.objects.get_or_create(name="Akan", frequency=16)[0]
Language.objects.get_or_create(name="Dinka", frequency=16)[0]
Language.objects.get_or_create(name="Gilaki", frequency=15)[0]
Language.objects.get_or_create(name="Hawaiian", frequency=15)[0]
Language.objects.get_or_create(name="Franco-Provençal", frequency=15)[0]
Language.objects.get_or_create(name="Romani", frequency=15)[0]
Language.objects.get_or_create(name="Chamorro", frequency=15)[0]
Language.objects.get_or_create(name="Aymara", frequency=14)[0]
Language.objects.get_or_create(name="Komi-Permyak", frequency=14)[0]
Language.objects.get_or_create(name="Greenlandic", frequency=14)[0]
aramaic = Language.objects.get_or_create(name="Aramaic", frequency=14)[0]
Language.objects.get_or_create(name="Tetum", frequency=14)[0]
Language.objects.get_or_create(name="Latgalian", frequency=14)[0]
Language.objects.get_or_create(name="Bambara", frequency=14)[0]
Language.objects.get_or_create(name="Adyghe", frequency=14)[0]
Language.objects.get_or_create(name="Tarantino", frequency=13)[0]
Language.objects.get_or_create(name="Võro", frequency=13)[0]
Language.objects.get_or_create(name="Kalmyk", frequency=13)[0]
Language.objects.get_or_create(name="Ingush", frequency=13)[0]
Language.objects.get_or_create(name="Pontic", frequency=13)[0]
Language.objects.get_or_create(name="Kinyarwanda", frequency=12)[0]
Language.objects.get_or_create(name="Tok Pisin", frequency=12)[0]
Language.objects.get_or_create(name="Lojban", frequency=12)[0]
Language.objects.get_or_create(name="Luganda", frequency=12)[0]
Language.objects.get_or_create(name="Kirundi", frequency=12)[0]
Language.objects.get_or_create(name="Pangasinan", frequency=11)[0]
Language.objects.get_or_create(name="Kabiye", frequency=11)[0]
Language.objects.get_or_create(name="Nauruan", frequency=11)[0]
Language.objects.get_or_create(name="Tahitian", frequency=11)[0]
Language.objects.get_or_create(name="Moksha", frequency=11)[0]
Language.objects.get_or_create(name="Cheyenne", frequency=11)[0]
Language.objects.get_or_create(name="Tsonga", frequency=11)[0]
Language.objects.get_or_create(name="Sesotho", frequency=11)[0]
Language.objects.get_or_create(name="Fijian", frequency=11)[0]
Language.objects.get_or_create(name="Inuktitut", frequency=11)[0]
Language.objects.get_or_create(name="Cree", frequency=11)[0]
Language.objects.get_or_create(name="Samoan", frequency=10)[0]
Language.objects.get_or_create(name="Tswana", frequency=10)[0]
Language.objects.get_or_create(name="Swati", frequency=10)[0]
navaho = Language.objects.get_or_create(name="Navajo", frequency=9)[0]
Language.objects.get_or_create(name="Karachay-Balkar", frequency=9)[0]
Language.objects.get_or_create(name="Karakalpak", frequency=9)[0]
Language.objects.get_or_create(name="Novial", frequency=9)[0]
Language.objects.get_or_create(name="Jamaican Patois", frequency=9)[0]
Language.objects.get_or_create(name="Kabardian", frequency=9)[0]
Language.objects.get_or_create(name="Kikuyu", frequency=9)[0]
Language.objects.get_or_create(name="Sranan", frequency=9)[0]
Language.objects.get_or_create(name="Kashmiri", frequency=9)[0]
Language.objects.get_or_create(name="Tongan", frequency=8)[0]
Language.objects.get_or_create(name="Inupiak", frequency=8)[0]
Language.objects.get_or_create(name="Northern Sotho", frequency=7)[0]
Language.objects.get_or_create(name="Lak", frequency=7)[0]
Language.objects.get_or_create(name="Kongo", frequency=7)[0]
Language.objects.get_or_create(name="Tumbuka", frequency=7)[0]
Language.objects.get_or_create(name="Sango", frequency=7)[0]
Language.objects.get_or_create(name="Fula", frequency=7)[0]
Language.objects.get_or_create(name="Pali", frequency=6)[0]
Language.objects.get_or_create(name="Ewe", frequency=6)[0]
Language.objects.get_or_create(name="Venda", frequency=6)[0]
Language.objects.get_or_create(name="Tigrinya", frequency=6)[0]
Language.objects.get_or_create(name="Herero", frequency=1)[0]
Language.objects.get_or_create(name="Ndonga", frequency=0)[0]
Language.objects.get_or_create(name="Choctaw", frequency=0)[0]
Language.objects.get_or_create(name="Marshallese", frequency=0)[0]
Language.objects.get_or_create(name="Kuanyama", frequency=0)[0]
Language.objects.get_or_create(name="Nuosu", frequency=0)[0]
Language.objects.get_or_create(name="Hiri Motu", frequency=0)[0]
Language.objects.get_or_create(name="Afar", frequency=0)[0]
Language.objects.get_or_create(name="Muscogee", frequency=0)[0]
Language.objects.get_or_create(name="Kanuri", frequency=0)[0]
algonquin = Language.objects.get_or_create(name="Algonquin", frequency=0)[0]
mayan = Language.objects.get_or_create(name="Mayan", frequency=0)[0]
iroquois = Language.objects.get_or_create(name="Iroquois", frequency=0)[0]
sioux = Language.objects.get_or_create(name="Sioux", frequency=0)[0]
anguthimri = Language.objects.get_or_create(name="Anguthimri", frequency=0)[0]
