from characters.models.changeling.ctdhuman import CtDHuman
from django.views.generic import CreateView, DetailView, UpdateView

from core.views.approved_user_mixin import SpecialUserMixin


class CtDHumanDetailView(SpecialUserMixin, DetailView):
    model = CtDHuman
    template_name = "characters/changeling/ctdhuman/detail.html"


class CtDHumanCreateView(CreateView):
    model = CtDHuman
    fields = [
        "name",
        "description",
        "strength",
        "dexterity",
        "stamina",
        "perception",
        "intelligence",
        "wits",
        "charisma",
        "manipulation",
        "appearance",
        "alertness",
        "athletics",
        "brawl",
        "empathy",
        "expression",
        "intimidation",
        "streetwise",
        "subterfuge",
        "crafts",
        "drive",
        "etiquette",
        "firearms",
        "melee",
        "stealth",
        "academics",
        "computer",
        "investigation",
        "medicine",
        "science",
        "contacts",
        "mentor",
        "willpower",
        "age",
        "apparent_age",
        "hair",
        "eyes",
        "ethnicity",
        "nationality",
        "height",
        "weight",
        "sex",
        "childhood",
        "history",
        "goals",
        "notes",
        "kenning",
        "leadership",
        "animal_ken",
        "larceny",
        "performance",
        "survival",
        "enigmas",
        "gremayre",
        "law",
        "politics",
        "technology",
        "chimera",
        "dreamers",
        "holdings",
        "remembrance",
        "resources",
        "retinue",
        "title",
        "treasure",
    ]
    template_name = "characters/changeling/ctdhuman/form.html"


class CtDHumanUpdateView(SpecialUserMixin, UpdateView):
    model = CtDHuman
    fields = [
        "name",
        "description",
        "strength",
        "dexterity",
        "stamina",
        "perception",
        "intelligence",
        "wits",
        "charisma",
        "manipulation",
        "appearance",
        "alertness",
        "athletics",
        "brawl",
        "empathy",
        "expression",
        "intimidation",
        "streetwise",
        "subterfuge",
        "crafts",
        "drive",
        "etiquette",
        "firearms",
        "melee",
        "stealth",
        "academics",
        "computer",
        "investigation",
        "medicine",
        "science",
        "contacts",
        "mentor",
        "willpower",
        "age",
        "apparent_age",
        "hair",
        "eyes",
        "ethnicity",
        "nationality",
        "height",
        "weight",
        "sex",
        "childhood",
        "history",
        "goals",
        "notes",
        "kenning",
        "leadership",
        "animal_ken",
        "larceny",
        "performance",
        "survival",
        "enigmas",
        "gremayre",
        "law",
        "politics",
        "technology",
        "chimera",
        "dreamers",
        "holdings",
        "remembrance",
        "resources",
        "retinue",
        "title",
        "treasure",
    ]
    template_name = "characters/changeling/ctdhuman/form.html"
