from characters import views
from django.urls import path

urls = [
    path(
        "charms/",
        views.werewolf.SpiritCharmCreateView.as_view(),
        name="spirit_charm",
    ),
    path(
        "spirits/",
        views.werewolf.SpiritCreateView.as_view(),
        name="spirit",
    ),
    path(
        "totems/",
        views.werewolf.TotemCreateView.as_view(),
        name="totem",
    ),
    path(
        "wtahuman/",
        views.werewolf.WtAHumanCreateView.as_view(),
        name="wta_human",
    ),
    path(
        "rites/",
        views.werewolf.RiteCreateView.as_view(),
        name="rite",
    ),
    path(
        "tribes/",
        views.werewolf.TribeCreateView.as_view(),
        name="tribe",
    ),
    path(
        "renownincidents/",
        views.werewolf.RenownIncidentCreateView.as_view(),
        name="renownincident",
    ),
    path(
        "battlescar/",
        views.werewolf.BattleScarCreateView.as_view(),
        name="battlescar",
    ),
    path(
        "gifts/",
        views.werewolf.GiftCreateView.as_view(),
        name="gift",
    ),
    path(
        "pack/",
        views.werewolf.PackCreateView.as_view(),
        name="pack",
    ),
    path(
        "fomor/",
        views.werewolf.FomorCreateView.as_view(),
        name="fomor",
    ),
    path(
        "werewolf/",
        views.werewolf.WerewolfCreateView.as_view(),
        name="werewolf",
    ),
    path(
        "kinfolk/",
        views.werewolf.KinfolkCreateView.as_view(),
        name="kinfolk",
    ),
    path(
        "camps/",
        views.werewolf.CampCreateView.as_view(),
        name="camp",
    ),
    path(
        "fomoripower/",
        views.werewolf.FomoriPowerCreateView.as_view(),
        name="fomoripower",
    ),
]
