from characters import views
from django.urls import path

urls = [
    path(
        "charms/<pk>/",
        views.werewolf.SpiritCharmUpdateView.as_view(),
        name="charm",
    ),
    path(
        "spirits/<pk>/",
        views.werewolf.SpiritUpdateView.as_view(),
        name="spirit",
    ),
    path(
        "totems/<pk>/",
        views.werewolf.TotemUpdateView.as_view(),
        name="totem",
    ),
    path(
        "wtahuman/<pk>/",
        views.werewolf.WtAHumanUpdateView.as_view(),
        name="wta_human",
    ),
    path(
        "rites/<pk>/",
        views.werewolf.RiteUpdateView.as_view(),
        name="rite",
    ),
    path(
        "tribes/<pk>/",
        views.werewolf.TribeUpdateView.as_view(),
        name="tribe",
    ),
    path(
        "gifts/<pk>/",
        views.werewolf.GiftUpdateView.as_view(),
        name="gift",
    ),
    path(
        "renownincidents/<pk>/",
        views.werewolf.RenownIncidentUpdateView.as_view(),
        name="renownincident",
    ),
    path(
        "battlescar/<pk>/",
        views.werewolf.BattleScarUpdateView.as_view(),
        name="battlescar",
    ),
    path(
        "pack/<pk>/",
        views.werewolf.PackUpdateView.as_view(),
        name="pack",
    ),
    path(
        "fomor/<pk>/",
        views.werewolf.FomorUpdateView.as_view(),
        name="fomor",
    ),
    path(
        "werewolf/<pk>/",
        views.werewolf.WerewolfUpdateView.as_view(),
        name="werewolf",
    ),
    path(
        "kinfolk/<pk>/",
        views.werewolf.KinfolkUpdateView.as_view(),
        name="kinfolk",
    ),
    path(
        "camps/<pk>/",
        views.werewolf.CampUpdateView.as_view(),
        name="camp",
    ),
    path(
        "fomoripower/<pk>/",
        views.werewolf.FomoriPowerUpdateView.as_view(),
        name="fomoripower",
    ),
]
